POST http://idcbackend-env.eba-bmwvm95d.ap-south-1.elasticbeanstalk.com/userlogin
Content-Type: application/json

{
    "memberid":"IDC0002",
    "password":"1234"
}

###
POST http://idcbackend-env.eba-bmwvm95d.ap-south-1.elasticbeanstalk.com/userregister
Content-Type: application/json

{
    "memberid":"IDC0002",
    "name":"shiva",
    "password":"1234"
}

###
GET http://idcbackend-env.eba-bmwvm95d.ap-south-1.elasticbeanstalk.com/nextmemberid 

###
POST http://idcbackend-env.eba-bmwvm95d.ap-south-1.elasticbeanstalk.com/newlabtechrecord
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImdlbmVyYWwiLCJtZW1iZXJpZCI6IklEQzAwMDEiLCJpYXQiOjE2NTMyOTE5NzV9.31-HW3qB4p99F72v22fMhnncaiz1D8TPn7SlcSLmQNU
Content-Type: application/json

{
    "memberid":"IDC0001"
}

###
POST http://localhost:3005/newlabtechrecord
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImdlbmVyYWwiLCJtZW1iZXJpZCI6IklEQzAwMDEiLCJpYXQiOjE2NTMyOTE5NzV9.31-HW3qB4p99F72v22fMhnncaiz1D8TPn7SlcSLmQNU
Content-Type: application/json

{
    "memberid":"IDC0001"
}

###
GET http://idcbackend-env.eba-bmwvm95d.ap-south-1.elasticbeanstalk.com/showuserrecord
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImdlbmVyYWwiLCJtZW1iZXJpZCI6IklEQzAwMDEiLCJpYXQiOjE2NTMyOTE5NzV9.31-HW3qB4p99F72v22fMhnncaiz1D8TPn7SlcSLmQNU

###
POST http://idcbackend-env.eba-bmwvm95d.ap-south-1.elasticbeanstalk.com/doctorlogin
Content-Type: application/json

{
    "mobile":"1234567899",
    "password":"1234"
}
###
POST http://localhost:3005/doctorlogin
Content-Type: application/json

{
    "mobile":"1234567899",
    "password":"1234"
}

###
GET http://idcbackend-env.eba-bmwvm95d.ap-south-1.elasticbeanstalk.com/showuserrecord/IDC0001
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImRvY3RvciIsIm1vYmlsZSI6IjEyMzQ1Njc4OTkiLCJpYXQiOjE2NTMzMDQxMTR9.Ld3e_ABbsm6vvQmsh8bIyxQF06bC4HaZzGIIPQoHmDw

###
POST http://idcbackend-env.eba-bmwvm95d.ap-south-1.elasticbeanstalk.com/getusermemberid
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6ImdlbmVyYWwiLCJtZW1iZXJpZCI6IklEQzAwMDEiLCJpYXQiOjE2NTMzMDU0OTN9.RllbMFNnFFMiZv7Wvy4jWqwiCrJNPs2OIrL655oiejs

###
GET https://us-central1-idc2022-e8f19.cloudfunctions.net/app/nextmemberid